platforms:
  twitter:
    names:
      - id: "dotey"
        name: "宝玉"
        xgoid: 97f1484ae48c430fbbf3438099743674
      - id: "AnthropicAI"
        name: "AnthropicAI"
        xgoid: fc28a211471b496682feff329ec616e5
      - id: "OpenAI"
        name: "OpenAI"
        xgoid: 0c0856a69f9f49cf961018c32a0b0049
      - id: "op7418"
        name: "歸藏"
        xgoid: 831fac36aa0a49a9af79f35dc1c9b5d9
    rss_url: 
      - https://api.xgo.ing/rss/user/{xgoid}
  
  weibo:
    names:
      - id: "5722964389"
        name: "GitHub中国官方微博"
    rss_url: 
      - https://rsshub.bestblogs.dev/weibo/user/{username}
      - https://rsshub.pseudoyu.com/weibo/user/{username} 