platforms:
  twitter:
    names:
      - id: "GitHub_Daily"
        name: "GitHub每日精选推文"
      - id: "dotey"
        name: "宝玉"
      - id: "AnthropicAI"
        name: "AnthropicAI"
      - id: "OpenAI"
        name: "OpenAI"
      - id: "op7418"
        name: "歸藏"
      - id: "hq4ai"
        name: "汗青 HQ"
    rss_url: 
      - https://rsshub.pseudoyu.com/twitter/user/{username}/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&showTimestampInDescription=1&showQuotedInTitle=1
      - https://rsshub.pseudoyu.com/x/user/{username}/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&showTimestampInDescription=1&showQuotedInTitle=1
      - https://rsshub.bestblogs.dev/twitter/user/{username}/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&showTimestampInDescription=1&showQuotedInTitle=1
      - https://rsshub.bestblogs.dev/x/user/{username}/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&showTimestampInDescription=1&showQuotedInTitle=1
  
  weibo:
    names:
      - id: "5722964389"
        name: "GitHub中国官方微博"
    rss_url: 
      - https://rsshub.bestblogs.dev/weibo/user/{username}
      - https://rsshub.pseudoyu.com/weibo/user/{username} 